### ISSUE TITLE
python3-ecosystem module builds failing due to new cryptography version

### ISSUE THREAD

**Issue by ncoghlan** [modularity-modules/python3#7]
Attempting to run `mbs-build local` is currently failing for me, with at least `python3-cryptography` failing to build:

```
ERROR: Command failed: 
 # /usr/bin/dnf builddep --installroot /var/lib/mock/module-python3-ecosystem-make-requests-installable-20171011080225-Thread-32/root/ /var/lib/mock/module-python3-ecosystem-make-requests-installable-20171011080225-Thread-32/root//builddir/build/SRPMS/python-cryptography-2.1-1.module+557d1ef8.src.rpm
Last metadata expiration check: 0:00:00 ago on Tue 17 Oct 2017 18:59:21 AEST.
No matching package to install: 'python2-cryptography-vectors = 2.1'
No matching package to install: 'python3-cryptography-vectors = 2.1'
Package python3-setuptools-36.2.0-7.fc28.noarch is already installed, skipping.
Not all dependencies satisfied
Error: Some packages could not be found.
```

This appears to be due to a new version of cryptography being checked in to Rawhide: https://src.fedoraproject.org/rpms/python-cryptography/c/8a8b99cdc919c80a2190ec77fd66d0b8bb1b1592?branch=master

The module build is picking up *this* change, but the build *environment* isn't picking up the corresponding change to the python-cryptography-vectors build dependency: https://src.fedoraproject.org/rpms/python-cryptography-vectors/c/c78fdd23ad8d961666d3351de1a57de15c391dbf?branch=master

**Comment by ncoghlan** [comment]
Related mbs-build issue: https://pagure.io/fm-orchestrator/issue/741

**Comment by ncoghlan** [comment]
@tiran Do you have an ETA for when the new python-crytography version is likely to make it's way through to Rawhide? It looks like you may have uncovered a "fun" problem with the new module build infrastructure for cases like this one where python-cryptography has a version-locked build dependency on python-cryptography-vectors.

I'm hoping the immediate problem will go away once the built RPMs are available in Rawhide.

**Comment by tiran** [comment]
I pushed the package to rawhide last week. The builds are:

* https://koji.fedoraproject.org/koji/buildinfo?buildID=984066 for ``python2-cryptography-vectors-2.1-1.fc28.noarch.rpm`` and ``python3-cryptography-vectors-2.1-1.fc28.noarch.rpm``
* https://koji.fedoraproject.org/koji/buildinfo?buildID=984069 ``python2-cryptography-2.1-1.fc28.x86_64.rpm`` and ``python3-cryptography-2.1-1.fc28.x86_64.rpm``

Since I was able to build python-cryptography 2.1, the vectors package must be available. After all the build depends on the package. I can see the files on mirrors such as https://ftp.halifax.rwth-aachen.de/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/p/ , too.

**Comment by ncoghlan** [comment]
Yeah, it's now looking like this is a bug in the way the python3-ecosystem module is defined - it isn't making sure it uses consistent versions of those two modules, but is also configured to pull `python-cryptography` from Rawhide.

I missed it that originally, since I don't know the `modulemd` definition format very well yet.

**Comment by ncoghlan** [comment]
https://src.fedoraproject.org/modules/python3-ecosystem/pull-request/1 *should* fix the build dependency issue, but ensuring that the buildroot includes the matching version of python-cryptography-vectors when python-cryptography gets updated.

**Comment by ncoghlan** [comment]
Local builds are still failing for me though, since neither that nor the python-custodia dependencies are getting loaded back into the build root.

**Comment by whitel** [comment]
@jkaluza do you have any ideas about the mbs-build local part of this?

**Comment by hanzz** [comment]
> Local builds are still failing for me though, since neither that nor the python-custodia dependencies are getting loaded back into the build root.

This is known issue caused by filters being applied to early for local builds. Try removing filters section and this should work locally.

**Comment by hanzz** [comment]
https://pagure.io/fm-orchestrator/issue/742

**Comment by ncoghlan** [comment]
@hanzz Thanks, I'll try that tomorrow.

**Comment by hanzz** [comment]
I will try to fix that on MBS side tomorrow too, but it will take some time before it's available in form of package.

**Comment by KarstenHopp** [comment]
I don't think that's the issue here. I've tried building that module as well and it looks like this:
rpm -qp --provides python3-cryptography-vectors-2.1-1.module+ff6cf7b7.noarch.rpm 
python3-cryptography-vectors = 2.1-1.module+ff6cf7b7
                                                              ^^^^^

And one of the failures is:
No matching package to install: 'python3-cryptography-vectors = 2.1'
                                                                                                           ^^^

That is a packaging error in python-cryptography-vectors:
Provides:       python-%{srcname} = %{version}-%{release}
                                                                                 ^^^

**Comment by ignatenkobrain** [comment]
@KarstenHopp I still don't get what you are trying to say here.... =(

**Comment by ignatenkobrain** [comment]
I tried to re-read 5 times and still no luck.

**Comment by tiran** [comment]
The line ``Provides: python-%{srcname} = %{version}-%{release}`` is not used on Fedora and it's only relevant for python2 package for RHEL 7. The python3 package uses ``%{?python_provide:%python_provide python%{python3_pkgversion}-%{srcname}}``. Also ``Requires: python3-cryptography-vectors = 2.1`` should match any 2.1 release.

**Comment by ncoghlan** [comment]
Aye, while the distro-dependent conditionals mean that the python-cryptography-vectors spec file isn't particularly easy to read, I can see the right RPMs are being generated in the local module build directory once I made the change at https://src.fedoraproject.org/modules/python3-ecosystem/pull-request/1

So I'm glad @hanzz chimed in, or I would have spent today being *very* confused about why it wasn't working :)

**Comment by ncoghlan** [comment]
As per https://github.com/modularity-modules/python3/issues/6#issuecomment-337287958, @mhlavink is working on a fix for both this and python-requests runtime dependency problem.

**Comment by ncoghlan** [comment]
@mhlavink's commit at https://src.fedoraproject.org/modules/python3-ecosystem/c/f2e33f6851aec5f5e22d4e00c6484d1a21b587f3?branch=master should resolve this issue.
